version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: two_gis
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data1
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: